# recommended name: `task name` + `model name`
name: radfusion
phase: train

common:
  # on macOS, if gpu_ids = 0 and mps.is_available
  # torch will use `mps`
  gpu_ids: -1
  cudnn_benchmark: False
  rand_seed: 42
  joint_training: True
  data_dir: data
  save_dir: logs
  results_dir: results

  num_epochs: 1
  num_classes: 1
  num_workers: 4

  optimizer: sgd
  learning_rate: 0.01
  sgd_momentum: 0.9
  sgd_dampening: 0.9
  weight_decay: 0.001
  # log
  num_visual: 8
  epochs_per_eval: 1
  epochs_per_save: 1
  iters_per_print: 8
  iters_per_visual: 8000
  max_ckpts: 2
  best_ckpt_metric: val_AUROC

joint:
  # task
  # when ckpt_path is not `None`, use it directly
  # otherwise, try to load the submodels' ckpt individually.
  model: FusionModel
  ckpt_path:
  dataset: MultimodalDataset
  use_pretrained: False
  num_epochs: 1
  batch_size: 8
  # optimizer
  optimizer: sgd
  learning_rate: 0.01
  sgd_momentum: 0.9
  sgd_dampening: 0.9
  weight_decay: 0.001
  # scheduler
  lr_decay_step: 600000
  lr_scheduler: cosine_warmup
  lr_warmup_steps: 10000
  # log
  num_visual: 8
  epochs_per_eval: 1
  epochs_per_save: 1
  iters_per_print: 8
  iters_per_visual: 8000
  max_ckpts: 2
  best_ckpt_metric: val_AUROC
ct:
  model: PENetClassifier
  dataset: pe
  phase: all
  ckpt_path: ckpts/penet_best.pth
  use_pretrained: False
  feat_size: 2048
  # preprocessing
  abnormal_prob: 0.3
  include_normals: True
  agg_method: max
  crop_shape: [192, 192]
  resize_shape: [208, 208]

  pe_types: [central, segmental]
  use_hem: False
  do_classify: True

  # model definition    
  model_depth: 50
  num_classes: 1
  num_epochs: 1
  num_slices: 24
  batch_size: 8

  optimizer: sgd
  learning_rate: 0.01
  sgd_momentum: 0.9
  sgd_dampening: 0.9
  weight_decay: 0.001

  lr_decay_step: 600000
  lr_scheduler: cosine_warmup
  lr_warmup_steps: 10000
  # post processing
  fine_tune: True
  fine_tuning_boundary: calssifier
  fine_tuning_lr: 0.01

ehr:
  model: ElasticNet
  data_dir: data
  dataset: EHRDataset
  ckpt_path: ckpts/elasticnet.pth
  use_pretrained: False
  feat_size: 200

  num_classes: 1
  num_epochs: 25
  batch_size: 128
  train_split: 0.7

  optimizer: sgd
  learning_rate: 0.01
  sgd_momentum: 0.9
  sgd_dampening: 0.9
  
  weight_decay: 0.001
  l1_ratio: 0.1
  alpha: 0
  n_early_stopping: -1
